apiVersion: v1
kind: ConfigMap
metadata:
  name: taskapp-config
  namespace: taskapp
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "taskdb"
  DB_USER: "taskuser"
  FLASK_ENV: "production"
